#ifndef CONFIG_H
#define CONFIG_H

#define RSA_CLIENT_KEY_LENGTH 2048
#define RSA_SERVER_KEY_LENGTH 4096
#define RSA_CA_KEY_LENGTH 4096
#define AES_KEY_LENGTH 128

#define RSA_PUBLIC_EXP 65537
#define AES_BLOCK_LENGTH 128
#define MAC_LENGTH 128

#endif // CONFIG_H
