#ifndef CONFIG_H
#define CONFIG_H

#define PING 0
#define OK 1
#define SEND_LOGIN_TO_SERVER 2
#define REQUEST_CLIENT_LIST_FROM_SERVER 3
#define REQUEST_CALL_TO_CLIENT_FROM_SERVER 4
#define SEND_CLIENT_LIST_TO_CLIENT 5
#define SEND_INCOMMING_CALL_TO_CLIENT 6
#define END_OF_CALL_TO_CLIENT 7
#define ERROR_SERVER_RESPONSE 666

#endif // CONFIG_H
